"use client";
import {useEffect,useRef,useState} from "react";
type Train={number:string;name:string;type:string;departure:string;arrival:string;duration:string;distance:number|null;classCode:string;availability:string;fare:number|null;delayMinutes:number|null;platform:string|null};
type Data={from:{code:string;name:string};to:{code:string;name:string};date:string;count:number;trains:Train[];fetchedAt:string};
export default function Home(){
 const[from,setFrom]=useState("NDLS"),[to,setTo]=useState("LKO"),[date,setDate]=useState(()=>new Date(Date.now()+86400000).toISOString().slice(0,10));
 const[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const searched=useRef(false),abort=useRef<AbortController|null>(null);
 async function search(){searched.current=true;abort.current?.abort();abort.current=new AbortController();setLoading(true);setError("");setData(null);try{const q=new URLSearchParams({from,to,date,_:String(Date.now())});const r=await fetch(`/api/trains?${q}`,{cache:"no-store",signal:abort.current.signal,headers:{"Cache-Control":"no-cache"}});const b=await r.json();if(!r.ok)throw new Error(b.error||"Live train search failed");setData(b)}catch(e){if((e as Error).name!=="AbortError")setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{if(!searched.current)return;const id=setTimeout(search,350);return()=>clearTimeout(id)},[date]);
 return <main><header><a className="brand"><b>R</b><span>RailVista<small>journeys, beautifully simple</small></span></a><nav>Live search　 Help</nav><i>KR</i></header>
 <section className="hero"><div><small>INDIA, CONNECTED</small><h1>Every journey<br/><em>begins beautifully.</em></h1><p>Date-specific trains, current seat status and fare—fetched fresh for every search.</p><span>✓ Fresh API request　 ✓ Live availability　 ✓ No cached results</span></div><figure/></section>
 <section className="search"><label>FROM<input value={from} onChange={e=>setFrom(e.target.value.toUpperCase())} placeholder="NDLS"/><small>Station code, e.g. NDLS</small></label><button className="swap" onClick={()=>{setFrom(to);setTo(from)}}>⇄</button><label>TO<input value={to} onChange={e=>setTo(e.target.value.toUpperCase())} placeholder="LKO"/><small>Station code, e.g. LKO</small></label><label>JOURNEY DATE<input type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label>QUOTA<strong>General (GN)</strong><small>Live class per train</small></label><button className="primary" disabled={loading||!from||!to||!date} onClick={search}>{loading?"Searching live…":"Search live trains →"}</button></section>
 <section className="content">{!data&&!loading&&!error&&<div className="title"><div><small>LIVE TRAIN SEARCH</small><h2>Search with station codes.</h2></div><p>Example: NDLS to LKO. Date change ke baad fresh request automatically hogi.</p></div>}
 {loading&&<div className="title"><div><small>CONTACTING RAIL SERVICE</small><h2>Fresh results aa rahe hain…</h2></div><p>Train, seat status aur fare verify ho rahe hain.</p></div>}
 {error&&<div className="title"><div><small>SEARCH FAILED</small><h2>Koi result load nahi hua.</h2></div><p>{error}</p></div>}
 {data&&<><div className="resultHead"><h2>{data.from.name} <em>→</em> {data.to.name}</h2><p>{data.date} · {data.count} trains found · refreshed {new Date(data.fetchedAt).toLocaleTimeString("en-IN")}</p></div>
 {data.trains.length===0&&<div className="title"><div><small>NO TRAINS</small><h2>Selected date par koi running train nahi mili.</h2></div><p>Date ya station code change karke dobara search karein.</p></div>}
 {data.trains.map(t=><article className="train" key={t.number+"-"+t.classCode}><div><small className="tag">{t.type}</small><h3>{t.name}</h3><span>#{t.number}{t.platform?` · Platform ${t.platform}`:""}</span><b className="ontime">{t.delayMinutes==null?"Live status unavailable":t.delayMinutes===0?"● On time":`● ${t.delayMinutes} min late`}</b></div><section><strong>{t.departure}<small>{data.from.name} ({data.from.code})</small></strong><label><small>{t.duration}{t.distance?` · ${t.distance} km`:""}</small><hr/>●</label><strong>{t.arrival}<small>{data.to.name} ({data.to.code})</small></strong></section><footer><span>Class <b>{t.classCode}</b>　 <b>{t.availability}</b></span><aside><small>fare</small><b>{t.fare==null?"Unavailable":`₹${Number(t.fare).toLocaleString("en-IN")}`}</b></aside></footer></article>)}</>}</section>
 <footer className="pagefoot"><span>RailVista</span><small>Independent demo · Not affiliated with Indian Railways or IRCTC · Verify before travel</small></footer></main>
}
